export const assets = [
    {url: "./cactus1.png", name: "Cactus 1"},
    {url: "./cactus2.png", name: "Cactus 2"},

    {url: "./parallax/bg0.png", name: "Background 0"},
	{url: "./parallax/bg1.png", name: "Background 1"},
	{url: "./parallax/bg2.png", name: "Background 2"},
	{url: "./parallax/bg3.png", name: "Background 3"},
	{url: "./parallax/bg4.png", name: "Background 4"},
	{url: "./parallax/bg5.png", name: "Background 5"},
	{url: "./parallax/bg6.png", name: "Background 6"},

	{url: "./dino/dead/dead1.png", name: "DinoDead0"},
	{url: "./dino/dead/dead2.png", name: "DinoDead1"},
	{url: "./dino/dead/dead3.png", name: "DinoDead2"},
	{url: "./dino/dead/dead4.png", name: "DinoDead3"},
	{url: "./dino/dead/dead5.png", name: "DinoDead4"},
	{url: "./dino/dead/dead6.png", name: "DinoDead5"},
	{url: "./dino/dead/dead7.png", name: "DinoDead6"},
	{url: "./dino/dead/dead8.png", name: "DinoDead7"},

	{url: "./dino/idle/idle1.png", name: "DinoIdle0"},
	{url: "./dino/idle/idle2.png", name: "DinoIdle1"},
	{url: "./dino/idle/idle3.png", name: "DinoIdle2"},
	{url: "./dino/idle/idle4.png", name: "DinoIdle3"},
	{url: "./dino/idle/idle5.png", name: "DinoIdle4"},
	{url: "./dino/idle/idle6.png", name: "DinoIdle5"},
	{url: "./dino/idle/idle7.png", name: "DinoIdle6"},
	{url: "./dino/idle/idle8.png", name: "DinoIdle7"},
	{url: "./dino/idle/idle9.png", name: "DinoIdle8"},
	{url: "./dino/idle/idle10.png", name: "DinoIdle9"},

	{url: "./dino/jump/jump1.png", name: "DinoJump0"},
	{url: "./dino/jump/jump2.png", name: "DinoJump1"},
	{url: "./dino/jump/jump3.png", name: "DinoJump2"},
	{url: "./dino/jump/jump4.png", name: "DinoJump3"},
	{url: "./dino/jump/jump5.png", name: "DinoJump4"},
	{url: "./dino/jump/jump6.png", name: "DinoJump5"},
	{url: "./dino/jump/jump7.png", name: "DinoJump6"},
	{url: "./dino/jump/jump8.png", name: "DinoJump7"},
	{url: "./dino/jump/jump9.png", name: "DinoJump8"},
	{url: "./dino/jump/jump10.png", name: "DinoJump9"},
	{url: "./dino/jump/jump11.png", name: "DinoJump10"},
	{url: "./dino/jump/jump12.png", name: "DinoJump11"},

	{url: "./dino/run/run1.png", name: "DinoRun0"},
	{url: "./dino/run/run2.png", name: "DinoRun1"},
	{url: "./dino/run/run3.png", name: "DinoRun2"},
	{url: "./dino/run/run4.png", name: "DinoRun3"},
	{url: "./dino/run/run5.png", name: "DinoRun4"},
	{url: "./dino/run/run6.png", name: "DinoRun5"},
	{url: "./dino/run/run7.png", name: "DinoRun6"},
	{url: "./dino/run/run8.png", name: "DinoRun7"},

	{url: "./dino/walk/walk1.png", name: "DinoWalk0"},
	{url: "./dino/walk/walk2.png", name: "DinoWalk1"},
	{url: "./dino/walk/walk3.png", name: "DinoWalk2"},
	{url: "./dino/walk/walk4.png", name: "DinoWalk3"},
	{url: "./dino/walk/walk5.png", name: "DinoWalk4"},
	{url: "./dino/walk/walk6.png", name: "DinoWalk5"},
	{url: "./dino/walk/walk7.png", name: "DinoWalk6"},
	{url: "./dino/walk/walk8.png", name: "DinoWalk7"},
	{url: "./dino/walk/walk9.png", name: "DinoWalk8"},
	{url: "./dino/walk/walk10.png", name: "DinoWalk9"},



];